#+TITLE: #TIL
#+DATE: <2023-01-01>

* [2023-01-17 Tue 19:33]

今天不得了了！我学到了太多有趣的东西。单说 Emacs，首先我了解到了我是完全可以使用 eshell over tramp 的（之前我都是用的 remote server 的 shell，存在 Tabnine 补全卡顿甚者 C-g 之后在 current session 就再也不好用的情况，等等）；其次在这个基础上，我知道了终止命令可以是 C-q C-c 而不需要再 list-process 然后 kill 掉，导致要重开 session；还有 eshell 的 C-up/down、Emacs 的 C-s 代替 reverse search 等等等等。😄

* [2023-01-17 Tue 19:57]

我还解决了 Hugo 的 invalid timezone 的问题；用 Emacs 和 Copilot 快速完成了段代码实现了 sticky post（网站文章置顶）的功能。

我跟老陈说 Emacs 我学得晚了，真的是太晚了，每每想到这我都感到焦虑，夜不能寐那种。老陈说你也不必这样，你还记得老李之前说过 I wish I had all the time I’d ever wasted, so I could waste it all over again 嘛？我们应该去享受过程不是吗？！我听了心里舒服多了。

对了，骇客邦 #30 已经寄出了，题目叫「人生苦短，要去折腾真正有意义的事情」。虽然意义众口难调，my honey and his arsenic, anyway, Substack, see you there. ❤️

* [2023-01-03 Tue 21:04]

需要把 700 多个文件重命名，涉及到删、改和部分大小写转换，这活儿按照我本来的想法是得整一个 shell 脚本跑一遍的，用 Emacs 初始化了脚本后我突然想到也许 Emacs 的 dired 模式下可以快速完成吧？于是进入了 dired，dired-toggle-read-only，再然后就是在其中直接 query-replace 和借用正则尽情翱翔了，最后 wdired-finish-edit 退出，完成。

全程约 7 分钟，含 Google 约 1 分钟，感动加感慨了约 2 分钟，实际操作约 4 分钟。

按理说已经学习了 2 年 Emacs，我应该非常平静和冷淡地看待这件事才是，但我仍无法淡定，因为我发现在 Emacs 面前我还是像个才入门的菜鸡一样。

2 年了，不能说急切，哥都焦虑了，夜不能寐那种。