#+TITLE: 无题
#+DATE: <2023-01-01>

* [2023-08-10 Thu 10:45]

最近写 Emacs Lisp 代码的节奏和感觉非常好。

首先是上月底我发现有道词典的调用开始不好用了，于是 3 号写了一个功能直接本地 GoldenDict，彻底摆脱远端依赖。

然后 4 号那天我写了解密 GPG 文件的功能。

7 号我写了挂载 TrueCrypt/VeraCrypt Volume 的功能。

9 号我可以备份我的 straight.el repos 到我的 NAS 并检查 NAS 确保只存有最近的 10 个存档备份。

今天我可以取消挂载 Volume 了。

就在刚才，我加了 3 个 schedule timer：每天上午备份 repos，每天上午挂载位于 NAS 的 Volume 然后傍晚取消。

* [2023-03-07 Tue 05:51]

我越来越认识到要凭借一己之力去管理一个开源项目需要很多技术以外的能力和性格特点，比如：

- 清楚表达----既能够把复杂的技术细节讲清楚，也能够把复杂简单化和通俗化
- 统筹规划----iteration changes 和 roadmap 等等
- 沟通能力
- 始终好奇并保持探索
- 等等

这些在 Jonas 的 EmacsSQL 4.0.0 里体现得淋漓尽致：

https://github.com/magit/emacsql/issues/113

* [2023-02-23 Thu 21:49]

我这两年在学习 Emacs，同时读了很多很多 Richard Stallman 的文章。现在我已经可以每天大部分的电脑时间生活在 Emacs 中，包括读写邮件。但仍然无法摆脱 X System，要断网了的话，我想也应该会让我崩了……等我攒够了足够的勇气，我要像 RMS 一样。

* [2023-02-10 Fri 23:43]

下午开会的时候，老王发消息给我，问我之前写的代码是基于哪个版本的？我当时就懵了，实在太久远了，久远到我都想不起来代码是什么时候写的了……刚才翻了之前的日记，才知道那已经是 2019 年的事情了……

- https://note.jsntn.com/dr-1.0.html

想到自己甚至还把那一年的经历记录成了一篇心得体会。

快速翻了一遍，看到第一段：

> I'm not young anymore, and I always hope that I can produce something memorable.

笑到不行了 🤪

然后看到结尾：

> # EOF: You've come a long way.

就笑不出来了 😟

#时光就变成了烟

* [2023-02-03 Fri 21:20]

我发现我现在自己写点什么东西也懒得折腾什么富文本编辑了，发布的话也不用啥 WordPress 这些花哨的玩意儿了……我可能是上岁数了，也是累了。

就比如这篇 https://note.jsntn.com/bye-pc-ide.html

直接手机打开个纯文本一写，往 github 一推，远端 pipeline 自动咔咔一跑，完成了。

* [2023-02-02 Thu 23:00]

我开始更轻松地 commit 我的 .emacs.d 了（@github/jsntn/emacs.d），因为我现在终于理解了「过程」比「结果」重要，换句话说，什么才是最终的「结果」？这也不好定义。所以与其期待结果之后的成就感，不如享受过程中的点滴成长和进步。若「过程」是值得经历的，那么它就是值得记录的。
