name: CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@v3.0
      with:
       version: 24.5
    - uses: actions/checkout@v2
    - name: install html-xml-utils
      run: |
       sudo apt-get update && sudo apt-get install html-xml-utils
    - name: check version
      run: |
       emacs --version
    - name: emacs help
      run: |
       emacs --help
    - name: emacs processing
      run: |
       emacs --batch -Q --load scripts/config.el -f org-publish-all --kill
    - name: generate rss
      run: |
       pwd && ls -l && bash ./scripts/rss-roller --auto
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./html
       cname: note.jsntn.com
